### ISSUE TITLE
Example is broken - no such attribute 'pubsub'

### ISSUE THREAD

**Issue by davidmcnabnz** [scailer/microagent#6]
I attempted to run the example server in the 'examples' directory.

However, the example crashes with the following exception:

```
Traceback (most recent call last):
  File "redisServer.py", line 8, in <module>
    from microagent.tools.aioredis import AIORedisSignalBus, AIORedisBroker
  File "/usr/local/lib/python3.8/dist-packages/microagent/tools/aioredis.py", line 16, in <module>
    class AIORedisSignalBus(AbstractSignalBus):
  File "/usr/local/lib/python3.8/dist-packages/microagent/tools/aioredis.py", line 33, in AIORedisSignalBus
    mpsc: aioredis.pubsub.Receiver
AttributeError: module 'aioredis' has no attribute 'pubsub'

Is microagent broken, or is there something I need to do to make the example work, that's not yet written up in the docs?
```

Please advise

Cheers
David

**Comment by scailer** [comment]
Hi, David.

This is probably due to the fact that aioredis version is not freezed in the examples. Support of aioredis 2.0 will appear in version 1.4 in the coming days (maybe today). You can solve problem installing aioredis==1.3

Thanks for your report, I will take this into account in a future version.

All the best,
Dmitrii

**Comment by davidmcnabnz** [comment]
Thanks for the update and workaround, Dmitrii. I'll regress my aioredis to 1.3 and retry the examples, and look forward to your announcement of microagent becoming aioredis 2.0-ready.

Cheers
David

**Comment by scailer** [comment]
A new version, that supports aioredis 2.0, has been released.

All the best,
Dmitry

**Comment by davidmcnabnz** [comment]
Thanks so much, Dmitry. I've upgraded and the examples now work fine. I look forward to evaluating MicroAgent for a dozens-of-nodes infrastructure I'm working on.
